### ISSUE TITLE
add img size in html

### ISSUE THREAD

**Issue by Abbbyccc** [fac25/week2-project-Abby-Abdullah-Manoela#40]

**Comment by Abbbyccc** [comment]
Hi @flare-s, since you are woking on the styling would you mind to help to add the width and height to the HTML too, I ran the lighthouse for our website and i think the images load a bit slow. Thank you very much!!! let me know if you have any qeustions!

**Comment by flare-s** [comment]
Yes, no problem at all. Thanks, Abby.
